let suffixes: unit => Js.Array.t(string);
let companyName: (~format: int=?, unit) => option(string);
let companySuffix: unit => string;
let catchPhrase: unit => string;
let bs: unit => string;
let catchPhraseAdjective: unit => string;
let catchPhraseDescriptor: unit => string;
let catchPhraseNoun: unit => string;
let bsAdjective: unit => string;
let bsBuzz: unit => string;
let bsNoun: unit => string;
